services:
  - type: web
    name: collide-dj5i  # your actual service name
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn usermgmt.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
    migrationsCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
