services:
  - type: web
    name: collide-dj5i  # Your actual service name on Render
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn usermgmt.wsgi:application
    autoDeploy: true
    migrationsCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
